Update issue 404
Trying to get the geometry from the shapefile seems to give back reasonable values, however, the following information and error is introduced:

02/02/2012 13:15:27  invest_cython_core DEBUG        pixel_size_x: 0.0333333333333
02/02/2012 13:15:27  invest_cython_core DEBUG        pixel_size_x: -0.0333333333333
02/02/2012 13:15:27  invest_cython_core DEBUG        top_left_x : -129.399822994
02/02/2012 13:15:27  invest_cython_core DEBUG        top_left_y : 49.8001729937
02/02/2012 13:15:27  invest_cython_core DEBUG        top_left_x : -129.36648966
02/02/2012 13:15:27  invest_cython_core DEBUG        top_left_y : 49.7668396603
02/02/2012 13:15:27  invest_cython_core DEBUG        point1 : (39605.663833307393, 5536090.2750156261, 0.0)
02/02/2012 13:15:27  invest_cython_core DEBUG        point2 : (41686.508410146344, 5532183.3570516277, 0.0)
02/02/2012 13:15:27  invest_cython_core DEBUG        pixel_diff_x : 2080.84457684
02/02/2012 13:15:27  invest_cython_core DEBUG        pixel_diff_y : -3906.917964
02/02/2012 13:15:27  wave_energy_core   DEBUG        X pixel size of DEM : 2080.844577
02/02/2012 13:15:27  wave_energy_core   DEBUG        Y pixel size of DEM : -3906.917964

ERROR 1: Attempt to create 207x-61 dataset is illegal,sizes must be larger than zero.

======================================================================
ERROR: test_wave_energy_biophysical (wave_energy_biophysical_test.TestWaveEnergyBiophysical)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dcdenu4/workspace/invest-natcap.invest-3/test/wave_energy_biophysical_test.py", line 20, in test_wave_energy_biophysical
    wave_energy_biophysical.execute(args)
  File "/home/dcdenu4/workspace/invest-natcap.invest-3/invest_python_environment/lib/python2.6/site-packages/invest_natcap/wave_energy/wave_energy_biophysical.py", line 127, in execute
    wave_energy_core.biophysical(biophysical_args)
  File "/home/dcdenu4/workspace/invest-natcap.invest-3/invest_python_environment/lib/python2.6/site-packages/invest_natcap/wave_energy/wave_energy_core.py", line 155, in biophysical
    datatype, nodata, wave_energy_path, cutter)
  File "invest_cython_core.pyx", line 212, in invest_cython_core.createRasterFromVectorExtents (invest_cython_core/invest_cython_core.c:3512)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

----------------------------------------------------------------------
Ran 2 tests in 10.369s

FAILED (errors=1)


Former-commit-id: 56167cfa6589f805e5dd0f509557f6e88025643a