Did code review stuff.
New issue

This changeset broke a test case :

======================================================================
ERROR: A regression test for valuation file to make sure that the output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rpsharp/local/workspace/invest-natcap.invest-3/test/wave_energy_valuation_test.py", line 30, in test_wave_energy_valuation_regression
    wave_energy_valuation.execute(args)
  File "/home/rpsharp/local/workspace/invest-natcap.invest-3/invest_python_environment/lib/python2.6/site-packages/invest_natcap/wave_energy/wave_energy_valuation.py", line 85, in execute
    wave_energy_core.valuation(valuation_args)
  File "/home/rpsharp/local/workspace/invest-natcap.invest-3/invest_python_environment/lib/python2.6/site-packages/invest_natcap/wave_energy/wave_energy_core.py", line 844, in valuation
    wave_data_geom = wave_data_feat.GetGeometryRef()
AttributeError: 'NoneType' object has no attribute 'GetGeometryRef'

Former-commit-id: 8d810de85313a2a4f97968c1875bde3687c92d65