Update issue 25
Removing test_data/test_blank_input from the repository as part of troubleshooting an error I'm getting when I run this from within Arc:

Traceback (most recent call last):
  File "Z:\projects\invest3x\python\invest_core\carbon_core_test.py", line 41, in test_carbon_core_smoke
    os.remove(lulc_path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '../../test_data/test_blank_input